name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hi
        run: echo "hello"
      - name: Print goodbye
        run: echo "adddfffdios"
      

